routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/tasks/resolved','TasksController@resolvedTasks')->name('tasks.resolved');
Route::get('/tasks/approved','TasksController@approvedTasks')->name('tasks.approved');
Route::get('/tasks/{task}/self_assign','TasksController@selfReassignTask')->name('tasks.self_assign');
Route::get('/users/best_employee','UsersController@bestEmployee')->name('users.best_employee');
Route::resource('teams','TeamsController');
Route::resource('tasks','TasksController');
Route::resource('users','UsersController');
Route::put('/tasks/{task}/resolve','TasksController@resolve')->name('tasks.resolve');
Route::put('/tasks/{task}/giveup','TasksController@giveUp')->name('tasks.giveup');
Route::put('/tasks/{task}/approve','TasksController@approveTask')->name('tasks.approve');
Route::put('/tasks/{task}/unapprove','TasksController@unapproveTask')->name('tasks.unapprove');
Route::put('/tasks/{task}/update_self_assign','TasksController@updateSelfReassignTask')->name('tasks.update_self_assign');
Route::put('/tasks/{task}/system_assign','TasksController@systemReassignTask')->name('tasks.system_assign');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * RELATIONSHIP METHODS
     */

     public function tasks(){
         return $this->hasMany(Task::class,'assigned_to');
     }

     public function team(){
         return $this->belongsTo(Team::class);
     }

     public function statuses()
     {
         return $this->hasMany(Status::class);
     }

     /**
      * HELPER FUNCTIONS
      */
    public function getLeader(User $user)
    {
        $team_leader = User::where('team_id',$user->team_id)->where('role','leader')->get();
        return $team_leader;
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Team;
use Illuminate\Http\Request;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;
use Carbon\Carbon;

class UsersController extends Controller
{
    
    public function index()
    {
        if(auth()->user()->role === 'leader'){
            // dd('reached');
            $users = User::where('team_id',auth()->user()->team_id)->get();
        }else{
            $users = User::where('role','!=','manager')->get();
        }

        return view('users.index',compact([
            'users'
        ]));
    }

    public function create()
    {
        return view('users.create');
    }

    public function store(CreateUserRequest $request)
    {
        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' =>  \Illuminate\Support\Facades\Hash::make($request->password)
        ]);

        session()->flash('success','User created Successfully');
        return redirect(route('users.index'));

    }

    
    public function show(User $user)
    {
        //
    }

    public function edit(User $user)
    {
        $teams = Team::all();
        // dd($teams);
        return view('users.edit',compact([
            'teams',
            'user'
        ]));
    }

    public function update(UpdateUserRequest $request, User $user)
    {
        // dd($request);
        
            $user->name = $request->name;
            $user->email = $request->email;
            $user->team_id = $request->team_id;

            $user->save();

        session()->flash('success','User edited Successfully');
        return redirect(route('users.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }

    public function bestEmployee(User $user)
    {
        $date = Carbon::parse('2020-08-15');
        $myMonth = $date->month - 1;
        $start_month = Carbon::parse('2020-'. $myMonth .'-1 00:00');
        // echo($start_month);
        $end_month = Carbon::parse('2020-'. $myMonth .'-1 00:00')->addMonth()->subDay();
        // dd($end_month);

        $users = User::where('role','!=','manager')->where('role','!=','leader')->get();
        $effecient_user;
        $highest_completed_task_count = 0;
        foreach($users as $user)
        {
            // echo($user->statuses);
            $completed_task_count = $user->statuses()->where('approved_at','>=',$start_month)->where('approved_at','<=',$end_month)->get()->count();
            // dd($completed_task_count);
            if($completed_task_count >= $highest_completed_task_count)
            {
                $highest_completed_task_count = $completed_task_count;
                $effecient_user  = $user;
            }
        }
        dd($effecient_user);
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
    <div class="card-header">
        Add User
    </div>
    <div class="card-body">
        <form action="{{route('users.store')}}" method = "POST">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text"
                    value = "{{old('name')}}"
                    class = "form-control" @error('name') is-valid @enderror name = "name" id = "name">
                @error('name')
                    <p class = "text-danger">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input type="text"
                    value = "{{old('email')}}"
                    class = "form-control" @error('email') is-valid @enderror name = "email" id = "email">
                @error('email')
                    <p class = "text-danger">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input type="password"
                    value = "{{old('password')}}"
                    class = "form-control" @error('password') is-valid @enderror name = "password" id = "password">
                @error('password')
                    <p class = "text-danger">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">
                <button class = "btn btn-success" type="submit">Add User</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
    <div class="card-header">
        Edit User
    </div>
    <div class="card-body">
        <form action="{{route('users.update',$user->id)}}" method = "POST">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text"
                    value = "{{old('name',$user->name)}}"
                    class = "form-control" @error('name') is-valid @enderror name = "name" id = "name">
                @error('name')
                    <p class = "text-danger">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input type="text"
                    value = "{{old('email',$user->email)}}"
                    class = "form-control" @error('email') is-valid @enderror name = "email" id = "email">
                @error('email')
                    <p class = "text-danger">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">
                <label for="team_id">Assign to Team</label>
                <select name="team_id" id="team_id" class = "form-control">
                    @foreach($teams as $team)
                        @if($user->team_id === $team->id)
                            <option value="{{$team->id}}" selected>{{$team->name}}</option>
                        @else
                            <option value="{{$team->id}}">{{$team->name}}</option>
                        @endif
                    @endforeach
                </select>
                @error('team_id')
                    <p class = "text-danger">{{$message}}</p>
                @enderror
            </div>


            <div class="form-group">
                <button class = "btn btn-success" type="submit">Edit user</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')
@section('content')

<div class="d-flex justify-content-end mb-3">
    <a href="{{ route('users.create') }}" class= "btn btn-primary">Create User</a>
</div>
<div class="card">
    <div class="card-header">Users</div>
    <div class="card-body">
        <table class ="table table-bordered">
            <thead>
                <th>Name</th>
                <th>Email</th>
                <th>Team</th>
                <th>Role</th>
                <th>Actions</th>
            </thead>
            <tbody>
                @foreach($users as $user)
                    @if(!($user->id === auth()->id()))
                        <tr>
                            <td>
                                {{ $user->name}}
                            </td>
                            <td>
                                {{ $user->email}}
                            </td>
                            <td>
                                @if($user->team_id === null)
                                    {{ 'Still Not Assigned'}}
                                @else
                                    {{ $user->team->name}}
                                @endif
                            </td>
                            <td>
                                {{ $user->role}}
                            </td>
                            <td>
                                <a href="{{ route('users.edit',$user->id)}}" class = "btn btn-primary btn-sm">{{$user->team_id ? 'Edit' : 'Assign Team'}}</a>
                                <a href="#" class = "btn btn-danger btn-sm" data-toggle = "modal" data-target = "#deleteModal"
                                onclick="displayModalForm({{$user}})">Delete</a>
                            </td>
                        </tr>
                    @endif
                @endforeach
            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <form action="" method = "POST" id = "deleteForm">
        @csrf
        @method('DELETE')
        <div class="modal-body">
            <p>Are you sure you want to delete User?</p>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Delete User</button>
        </div>
    </form>
  </div>
</div>
</div>
@endsection

@section('page-level-scripts')
<script type = "text/javascript">
function displayModalForm($user){
    alert('reached');
    var url = "/users/" + $user.id;
    $("#deleteForm").attr('action',url);
}
</script>
@endsection