routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/tasks/resolved','TasksController@resolvedTasks')->name('tasks.resolved');
Route::get('/tasks/approved','TasksController@approvedTasks')->name('tasks.approved');
Route::get('/tasks/{task}/self_assign','TasksController@selfReassignTask')->name('tasks.self_assign');
Route::get('/users/best_employee','UsersController@bestEmployee')->name('users.best_employee');
Route::resource('teams','TeamsController');
Route::resource('tasks','TasksController');
Route::resource('users','UsersController');
Route::put('/tasks/{task}/resolve','TasksController@resolve')->name('tasks.resolve');
Route::put('/tasks/{task}/giveup','TasksController@giveUp')->name('tasks.giveup');
Route::put('/tasks/{task}/approve','TasksController@approveTask')->name('tasks.approve');
Route::put('/tasks/{task}/unapprove','TasksController@unapproveTask')->name('tasks.unapprove');
Route::put('/tasks/{task}/update_self_assign','TasksController@updateSelfReassignTask')->name('tasks.update_self_assign');
Route::put('/tasks/{task}/system_assign','TasksController@systemReassignTask')->name('tasks.system_assign');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Task extends Model
{

    protected $fillable = ['name','assigned_to','created_by'];
    /**
     * RELATIONSHIP METHODS
     */


     public function user()
     {
         return $this->belongsTo(User::class,'assigned_to');
     }

     public function statuses()
     {
         return $this->hasMany(Status::class);
     }

     /**
      * ACCESSOR METHODS
      */

      public function getStatusAttribute()
      {
          return $this->statuses()->latest()->first();
      }

     /**
      * HELPER METHODS
      */

      public function getTeamLeader(Task $task)
      {
        $team_leader = User::where('id',$task->created_by)->get();
        return $team_leader;
      }

}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Task;
use App\Status;
use App\User;
use App\Http\Requests\CreateTaskRequest;
use App\Http\Requests\UpdateTaskRequest;
use App\Http\Controllers\session;
use Illuminate\Http\Request;
use Carbon\Carbon;

class TasksController extends Controller
{
  
    public function index()
    {
        $tasks = collect();
        if(auth()->user()->role === 'member')
       {
            $tp = Task::where('assigned_to',auth()->id())->get();
            foreach($tp as $task){
                if($task->status->resolved_at == null && $task->status->gave_up_at == null){
                    // dd($task);
                    $tasks->push($task);
                } 
            }
            // dd($tasks);
        }else{
            $tp = Task::where('created_by',auth()->id())->get();
            foreach($tp as $task){
                // echo($task->statuses);
                // echo("<br><br>");
                if($task->status->resolved_at === null){
                        $tasks->push($task);
                } 
            }
        }
        // dd($tasks);
        return view('tasks.index',compact([
            'tasks'
        ]));
    }

 
    public function create()
    {
        $users = User::where('team_id',auth()->user()->team_id)->get();
        // dd($users);
        return view('tasks.create',compact([
            'users'
        ]));
    }
    public function store(CreateTaskRequest $request)
    {
        // dd('reached');
        $task = Task::create([
            'name' => $request->name,
            'assigned_to' => $request->assigned_to,
            'created_by' => auth()->id()
        ]);

        Status::create([
            'task_id' => $task->id,
            'user_id' => $request->assigned_to
        ]);
        
        session()->flash('success','Task created Successfully');
        return redirect(route('tasks.index'));
        
    }

  
    public function show(Task $task)
    {
        
    }

  
    public function edit(Task $task)
    {
        $users = User::where('team_id',auth()->user()->team_id)->get();
        return view('tasks.edit',compact([
            'users',
            'task'
        ]));
    }

  
    public function update(UpdateTaskRequest $request, Task $task)
    {
        $task->name = $request->name;
        $task->assigned_to = $request->assigned_to;
        // $task->statuses->task_id = $task->id;
        $task->save();
        $status = $task->status;
        // dd($status);
        $status->update([
            'user_id' => $request->assigned_to
        ]);
    
        session()->flash('success','Task updated Successfully');
        return redirect(route('tasks.index'));
    }

  
    public function destroy(Task $task)
    {
        
    }

    public function resolve(Task $task)
    {
        $status = $task->status;
        // dd($status);
        $status->update([
            'resolved_at' => \Carbon\Carbon::now()->toDateTimeString(),
        ]);
        // dd('done');
        session()->flash('success','Task has been resolved Successfully');
        return redirect(route('tasks.index'));
    }

    public function giveUp(Task $task)
    {
        $status = $task->status;
        // dd($status);
        $status->update([
            'gave_up_at' => \Carbon\Carbon::now()->toDateTimeString(),
        ]);
        // dd('done');
        session()->flash('success','Task has been given up Successfully');
        return redirect(route('tasks.index'));
    }

    public function resolvedTasks()
    {   
        $tasks = collect();
        $tp = Task::where('created_by',auth()->id())->get();
        // dd($tp);
        foreach($tp as $task){
            // echo($task->statuses);
            // echo("<br><br>");
            if($task->status->resolved_at !== null && $task->status->approved_at === null){
                    $tasks->push($task);
            } 
        }
        // dd($tasks);
        return view('tasks.resolved.index',compact([
            'tasks'
        ]));
    }

    public function approveTask(Task $task)
    {
        $status = $task->status;
        // dd($status);
        $status->update([
            'approved_at' =>  \Carbon\Carbon::now()->toDateTimeString(),
        ]);
    
        session()->flash('success','Task approved Successfully');
        return redirect(route('tasks.index'));
    }

    public function unapproveTask(Task $task)
    {
        $status = $task->status;
        // dd($status);
        $status->update([
            'resolved_at' =>  null,
        ]);
    
        session()->flash('success','Task unapproved Successfully');
        return redirect(route('tasks.index'));
    }

    public function approvedTasks()
    {   
        $tasks = collect();
        $tp = Task::where('created_by',auth()->id())->get();
        // dd($tp);
        foreach($tp as $task){
            // echo($task->statuses);
            // echo("<br><br>");
            if($task->status->approved_at !== null && $task->status->resolved_at !== null){
                    $tasks->push($task);
            } 
        }
        // dd($tasks);
        return view('tasks.approved.index',compact([
            'tasks'
        ]));
    }

    public function selfReassignTask(Task $task)
    {
        $users = User::where('team_id',auth()->user()->team_id)->where('id','!=',$task->assigned_to)->get();
        // dd($users);
        return view('tasks.re-assign.reassign',compact([
            'users',
            'task'
        ]));
    }

    public function updateSelfReassignTask(UpdateTaskRequest $request,Task $task)
    {
        $task->assigned_to = $request->assigned_to;
        $task->save();

        Status::create([
            'task_id' => $task->id,
            'user_id' => $request->assigned_to
        ]);
    
        session()->flash('success','Task Re-Assigned Successfully');
        return redirect(route('tasks.index'));   
    }

    public function systemReassignTask(Task $task)
    {
        $users = User::where('team_id',auth()->user()->team_id)->where('role','!=','leader')->where('id','!=',$task->assigned_to)->get();
        // dd($users);
        $free_users = collect();
        foreach($users as $user){
            if($user->tasks()->count() == 0){
                $free_users->push($user);
            }
        }
        // dd($free_users);
        if($users->count() == 1)
        {   
            $task->assigned_to = $users->id;
            $task->save();
            Status::create([
                'task_id' => $task->id,
                'user_id' => $users->id
            ]);

            session()->flash('success','Task Re-Assigned by the system Successfully');
            return redirect(route('tasks.index'));
        }else if($users->count() > 1 && $free_users->count() > 0){
            $task->assigned_to = $free_users->first()->id;
            $task->save();

            Status::create([
                'task_id' => $task->id,
                'user_id' => $free_users->first()->id
            ]);

            session()->flash('success','Task Re-Assigned by the system Successfully');
            return redirect(route('tasks.index'));
        }else if($users->count() > 1 && $free_users->count() == 0){
            // dd('reached');
            $previous_week_first_date = Carbon::parse('2020-07-08 00:00')->startOfWeek()->subWeek();
            $previous_week_last_date = Carbon::parse('2020-07-08 00:00')->startOfWeek();
            // dd($previous_week_last_date);
            $effecient_user;
            $highest_completed_task_count = 0;
            foreach($users as $user)
            {
                $completed_task_count = $user->statuses()->where('approved_at','<',$previous_week_last_date)->where('approved_at','>=',$previous_week_first_date)->get()->count();
                // dd($completed_task_count);
                if($completed_task_count >= $highest_completed_task_count)
                {
                    $highest_completed_task_count = $completed_task_count;
                    $effecient_user  = $user;
                }
            }
            // dd($effecient_user);
            $task->assigned_to = $effecient_user->id;
            $task->save();
            
            Status::create([
                'user_id' => $effecient_user->id,
                'task_id' => $task->id
            ]);

            session()->flash('success','Task Re-Assigned by the system Successfully');
            return redirect(route('tasks.index'));
        }
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
    <div class="card-header">
        Add Task
    </div>
    <div class="card-body">
        <form action="{{route('tasks.store')}}" method = "POST">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text"
                    value = "{{old('name')}}"
                    class = "form-control" @error('name') is-valid @enderror name = "name" id = "name">
                @error('name')
                    <p class = "text-danger">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">
                <label for="assigned_to">Assign to team member</label>
                <select name="assigned_to" id="assigned_to" class = "form-control">
                    @foreach($users as $user)
                        @if(!($user->role === 'leader'))
                            <option value="{{$user->id}}">{{$user->name}}</option>
                        @endif
                    @endforeach
                </select>
                @error('assigned_to')
                    <p class = "text-danger">{{$message}}</p>
                @enderror
            </div>


            <div class="form-group">
                <button class = "btn btn-success" type="submit">Add Task</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
    <div class="card-header">
        Edit Task
    </div>
    <div class="card-body">
        <form action="{{route('tasks.update',$task->id)}}" method = "POST">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text"
                    value = "{{old('name',$task->name)}}"
                    class = "form-control" @error('name') is-valid @enderror name = "name" id = "name">
                @error('name')
                    <p class = "text-danger">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">
                <label for="assigned_to">Assign to team member</label>
                <select name="assigned_to" id="assigned_to" class = "form-control">
                <option value="{{$task->assigned_to}}">{{$task->user->name}}</option>
                    @foreach($users as $user)
                        @if(!($user->role === 'leader'))
                            @if($task->assigned_to != $user->id)
                                <option value="{{$user->id}}">{{$user->name}}</option>
                            @endif
                        @endif
                    @endforeach
                </select>
                @error('assigned_to')
                    <p class = "text-danger">{{$message}}</p>
                @enderror
            </div>


            <div class="form-group">
                <button class = "btn btn-success" type="submit">Edit Task</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')
@section('content')

<div class="d-flex justify-content-end mb-3">
    @can('canEditDeleteCreateTask',auth()->user())
        <a href="{{ route('tasks.create') }}" class= "btn btn-primary mr-3">Create Task</a>
        <a href="{{route('tasks.resolved')}}" class = "btn btn-secondary mr-3">Resolved Tasks</a>
        <a href="{{route('tasks.approved')}}" class = "btn btn-success">Approved Tasks</a>
    @endcan
</div>
<div class="card">
<div class="card-header">
    @if(auth()->user()->role === 'member')
        Task Created By {{auth()->user()->getLeader(auth()->user())[0]['name']}}
    @else
        Tasks
    @endif
</div>
    <div class="card-body">
        @if($tasks->count()>0)
            <table class ="table table-bordered">
                <thead>
                    <th>Name</th>
                    <th>Assigned To</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($tasks as $task)
                        @if($task->status->gave_up_at === null)    
                            <tr>
                                <td>
                                    {{ $task->name}}
                                </td>
                                <td>
                                    {{ $task->user->name}}
                                </td>
                                <td>
                                    @can('canEditDeleteCreateTask',$task->user)
                                        <a href="{{ route('tasks.edit',$task->id)}}" class = "btn btn-primary btn-sm">Edit</a>
                                        <a href="#" class = "btn btn-danger btn-sm" data-toggle = "modal" data-target = "#deleteModal"
                                        onclick="displayModalForm({{$task}})">Delete</a>
                                    @else
                                        <div class="d-flex">
                                            <form action="{{ route('tasks.resolve',$task->id)}}" method="POST" class = "mr-3">
                                                @csrf
                                                @method('PUT')
                                                <button type = "submit" class = "btn btn-primary btn-sm">Resolve</button>
                                            </form>
                                            <form action="{{ route('tasks.giveup',$task->id)}}" method="POST">
                                                @csrf
                                                @method('PUT')
                                                <button type = "submit" class = "btn btn-danger btn-sm">Give Up</button>
                                            </form>
                                        </div>
                                    @endcan
                                </td>
                            </tr>
                        @endif
                    @endforeach
                </tbody>
            </table>
        @else
            <p>Nothing To Show</p>
        @endif
    </div>
</div>

@can('canEditDeleteCreateTask',auth()->user())
    <div class="card mt-4">
        <div class="card-header">
            Gave Up Tasks
        </div>
        <div class="card-body">
            @if($tasks->count()>0)
                <table class ="table table-bordered">
                    <thead>
                        <th>Name</th>
                        <th>Assigned To</th>
                        <th>Actions</th>
                    </thead>
                    <tbody>
                        @foreach($tasks as $task)
                            @if($task->status->gave_up_at !== null)
                                <tr>
                                    <td>
                                        {{ $task->name}}
                                    </td>
                                    <td>
                                        {{ $task->user->name}}
                                    </td>
                                    <td>
                                        <div class="d-flex">
                                            <a href="{{ route('tasks.self_assign',$task->id)}}" type = "submit" class = "btn btn-info btn-sm mr-3">Self Assign</a>
                                            <form action="{{ route('tasks.system_assign',$task->id)}}" method="POST">
                                                @csrf
                                                @method('PUT')
                                                <button type = "submit" class = "btn btn-warning btn-sm">System Assign</button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endif
                        @endforeach
                    </tbody>
                </table>
            @else
                <p>Nothing To Show</p>
            @endif
        </div>
    </div>
@endcan

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <form action="" method = "POST" id = "deleteForm">
        @csrf
        @method('DELETE')
        <div class="modal-body">
            <p>Are you sure you want to delete Task?</p>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Delete Task</button>
        </div>
    </form>
  </div>
</div>
</div>
@endsection

@section('page-level-scripts')
<script type = "text/javascript">
function displayModalForm($task){
    alert('reached');
    var url = "/tasks/" + $task.id;
    $("#deleteForm").attr('action',url);
}
</script>
@endsection