routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/tasks/resolved','TasksController@resolvedTasks')->name('tasks.resolved');
Route::get('/tasks/approved','TasksController@approvedTasks')->name('tasks.approved');
Route::get('/tasks/{task}/self_assign','TasksController@selfReassignTask')->name('tasks.self_assign');
Route::get('/users/best_employee','UsersController@bestEmployee')->name('users.best_employee');
Route::resource('teams','TeamsController');
Route::resource('tasks','TasksController');
Route::resource('users','UsersController');
Route::put('/tasks/{task}/resolve','TasksController@resolve')->name('tasks.resolve');
Route::put('/tasks/{task}/giveup','TasksController@giveUp')->name('tasks.giveup');
Route::put('/tasks/{task}/approve','TasksController@approveTask')->name('tasks.approve');
Route::put('/tasks/{task}/unapprove','TasksController@unapproveTask')->name('tasks.unapprove');
Route::put('/tasks/{task}/update_self_assign','TasksController@updateSelfReassignTask')->name('tasks.update_self_assign');
Route::put('/tasks/{task}/system_assign','TasksController@systemReassignTask')->name('tasks.system_assign');

resources/views/layouts/_message.blade.php
<div class="row">
    <div class="col-md-12">
        @if(session()->has('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ session()-> get('success')}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        @if(session()->has('error'))
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ session()-> get('error')}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
    </div>
</div>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    @yield('page-level-styles')
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @auth
                <div class="container">
                    @include('layouts._message')
                    <div class="row">
                        <div class="col-md-3">
                            <ul class="list-group">
                                @can('canViewUser',auth()->user())
                                    <li class="list-group-item">
                                        <a href="{{ route('users.index') }}">Users</a>
                                    </li>
                                @endcan
                                @can('canViewTeam',auth()->user())
                                    <li class="list-group-item">
                                        <a href="{{ route('teams.index') }}">Teams</a>
                                    </li>
                                @endcan
                                @can('canViewTask',auth()->user())
                                    <li class="list-group-item">
                                        <a href="{{route('tasks.index')}}">Tasks</a>
                                    </li>
                                @endcan
                                <li class="list-group-item">
                                    <a href="{{route('users.best_employee')}}">Best Employee</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-9">
                            @yield('content')
                        </div>
                    </div>
                </div>
            @else
                @yield('content')
            @endauth
        </main>
    </div>
<!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    @yield('page-level-scripts')
</body>
</html>